Repository onaio/reveal-frontend, pull requests merged in 2020-07, with the labels that each got.

#929 Improve plan assignments page
  .env.sample
  package.json
  src/App/App.tsx
  src/components/TreeWalker/SelectField.tsx
  src/components/TreeWalker/tests/index.test.tsx
  src/components/forms/PlanForm/tests/index.test.tsx
  src/configs/__mocks__/env.ts
  src/configs/env.ts
  src/configs/lang.ts
  src/configs/strings/en.json
  src/containers/pages/InterventionPlan/IRS/plan/index.tsx
  src/containers/pages/PlanAssignment/helpers/AssignedOrgs/index.tsx
  src/containers/pages/PlanAssignment/helpers/AssignedOrgs/tests/__snapshots__/index.test.tsx.snap
  src/containers/pages/PlanAssignment/helpers/AssignedOrgs/tests/index.test.tsx
  src/containers/pages/PlanAssignment/helpers/EditOrgs/index.tsx
  src/containers/pages/PlanAssignment/helpers/EditOrgs/tests/__snapshots__/index.test.tsx.snap
  src/containers/pages/PlanAssignment/helpers/EditOrgs/tests/index.test.tsx
  src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/helpers.ts
  src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/index.tsx
  src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/tests/__snapshots__/index.test.tsx.snap
  src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/tests/fixtures.ts
  src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/tests/helpers.test.ts
  src/containers/pages/PlanAssignment/helpers/JurisdictionAssignmentForm/tests/index.test.tsx
  src/containers/pages/PlanAssignment/helpers/JurisdictionCell/index.tsx
  src/containers/pages/PlanAssignment/helpers/JurisdictionCell/tests/__snapshots__/index.test.tsx.snap
  src/containers/pages/PlanAssignment/helpers/JurisdictionCell/tests/index.test.tsx
  src/containers/pages/PlanAssignment/helpers/JurisdictionTable/index.tsx
  src/containers/pages/PlanAssignment/helpers/JurisdictionTable/tests/__snapshots__/index.test.tsx.snap
  src/containers/pages/PlanAssignment/helpers/JurisdictionTable/tests/index.test.tsx
  src/containers/pages/PlanAssignment/helpers/types.ts
  src/containers/pages/PlanAssignment/index.tsx
  src/containers/pages/PlanAssignment/tests/__snapshots__/index.test.tsx.snap
  src/containers/pages/PlanAssignment/tests/index.test.tsx
  src/helpers/utils.tsx
  src/store/ducks/opensrp/assignments/index.ts
  src/store/ducks/opensrp/assignments/tests/index.test.tsx
  src/store/ducks/tests/fixtures.ts
Labels: QA+

#1021 Fix map jankiness
  src/components/GisidaLite/tests/index.test.tsx
  src/containers/pages/FocusInvestigation/map/active/tests/indexCases.test.tsx
Labels: WIP

#1063 Optional plan assignment map
  .env.sample
  src/configs/env.ts
  src/containers/pages/PlanAssignment/index.tsx
  src/containers/pages/PlanAssignment/tests/index.test.tsx
Labels: WIP

#1048 Add new/updated plans to store
  package.json
  src/components/forms/PlanForm/helpers.ts
  src/components/forms/PlanForm/index.tsx
  src/components/forms/PlanForm/tests/helpers.test.ts
  src/components/forms/PlanForm/tests/index.test.tsx
  src/containers/pages/InterventionPlan/NewPlan/General/index.tsx
  src/containers/pages/InterventionPlan/NewPlan/General/tests/index.test.tsx
  src/containers/pages/InterventionPlan/UpdatePlan/index.tsx
  src/containers/pages/InterventionPlan/UpdatePlan/tests/index.test.tsx
  yarn.lock
Labels: enhancement

#1074 Revert to initialize ReactMapboxGl inside GisidaLite component
  src/components/GisidaLite/index.tsx
Labels: bug

#1057 Disallow large snapshots
  .circleci/config.yml
  .eslintrc
  .eslintrc.js
  package.json
Labels: tests

#1073 Stop showing loader if user has no superset permissions
  src/containers/pages/FocusInvestigation/active/index.tsx
  src/containers/pages/FocusInvestigation/active/tests/index.test.tsx
Labels: enhancement
