Repository onaio/reveal-frontend, pull requests merged in 2020-03, with the labels that each got.

#731 Update indicator color and thresholds for IRS Namibia
  src/components/formatting/IRSIndicatorLegend/tests/__snapshots__/index.test.tsx.snap
  src/configs/settings.ts
Labels: enhancement

#726 Coverage report
  .circleci/config.yml
  README.md
  package.json
  yarn.lock
Labels: tests

#732 647 case details
  package.json
  src/configs/lang.ts
  src/configs/strings/en.json
  src/constants.tsx
  src/containers/pages/InterventionPlan/UpdatePlan/CaseDetails/index.css
  src/containers/pages/InterventionPlan/UpdatePlan/CaseDetails/index.tsx
  src/containers/pages/InterventionPlan/UpdatePlan/CaseDetails/tests/__snapshots__/index.test.tsx.snap
  src/containers/pages/InterventionPlan/UpdatePlan/CaseDetails/tests/index.test.tsx
  src/containers/pages/InterventionPlan/UpdatePlan/index.tsx
  src/containers/pages/InterventionPlan/UpdatePlan/tests/fixtures.tsx
  src/containers/pages/InterventionPlan/UpdatePlan/tests/index.test.tsx
  src/containers/pages/InterventionPlan/UpdatePlan/tests/utils.test.tsx
  src/containers/pages/InterventionPlan/UpdatePlan/utils.tsx
  src/store/ducks/opensrp/events/index.tsx
  src/store/ducks/opensrp/events/tests/fixtures.ts
  src/store/ducks/opensrp/events/tests/index.test.ts
  src/store/ducks/opensrp/events/utils.ts
Labels: WIP

#728 Refactor focus investigation map
  src/containers/pages/FocusInvestigation/map/active/helpers/MarkCompleteLink/index.tsx
  src/containers/pages/FocusInvestigation/map/active/helpers/MarkCompleteLink/tests/__snapshots__/index.test.tsx.snap
  src/containers/pages/FocusInvestigation/map/active/helpers/MarkCompleteLink/tests/index.test.tsx
  src/containers/pages/FocusInvestigation/map/active/helpers/StatusBadge/index.tsx
  src/containers/pages/FocusInvestigation/map/active/helpers/StatusBadge/tests/__snapshots__/index.test.tsx.snap
  src/containers/pages/FocusInvestigation/map/active/helpers/StatusBadge/tests/index.test.tsx
  src/containers/pages/FocusInvestigation/map/active/helpers/utils.tsx
  src/containers/pages/FocusInvestigation/map/active/index.tsx
  src/containers/pages/FocusInvestigation/map/active/tests/__snapshots__/index.test.tsx.snap
  src/containers/pages/FocusInvestigation/map/active/tests/fixtures.ts
  src/containers/pages/FocusInvestigation/map/active/tests/index.test.tsx
  src/helpers/handlers/index.ts
  src/store/ducks/tests/fixtures.ts
Labels: enhancement, tests

#753 Use explicit types for function params with any
  src/containers/pages/IRS/JurisdictionsReport/index.tsx
Labels: enhancement

#612 611 Add config for ra Zambia
  src/configs/settings.ts
  src/configs/types.ts
Labels: WIP

#754 Enhancement/641 ga tracking
  package.json
  server/src/configs/__mocks__/envs.ts
  server/src/configs/envs.ts
  server/src/index.ts
  server/src/tests/fixtures.ts
  server/src/tests/index.test.ts
  src/App/App.tsx
  src/App/tests/App.test.tsx
  src/components/page/WithGATracker/index.tsx
  src/components/page/WithGATracker/tests/index.test.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement
